# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="ชื่อสัญญา")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("service", "สัญญาบริการ"),
                            ("nda", "NDA"),
                            ("sla", "SLA"),
                            ("retainer", "Retainer"),
                            ("other", "อื่นๆ"),
                        ],
                        default="service",
                        max_length=10,
                        verbose_name="ประเภทสัญญา",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="วันเริ่มสัญญา")),
                ("end_date", models.DateField(verbose_name="วันหมดสัญญา")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="มูลค่าสัญญา (บาท)",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contracts/%Y/",
                        verbose_name="ไฟล์สัญญา",
                    ),
                ),
                (
                    "pdpa_compliant",
                    models.BooleanField(
                        default=False, verbose_name="ผ่าน PDPA Checklist"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expiring", "กำลังหมดอายุ"),
                            ("expired", "หมดอายุ"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="crm.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["end_date"],
            },
        ),
    ]
