# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "การตลาด / โฆษณา"),
                            ("tools_software", "เครื่องมือ / Software"),
                            ("hosting_infra", "Hosting / Infrastructure"),
                            ("llm_api", "LLM API (OpenAI, Claude ฯลฯ)"),
                            ("salary_payroll", "เงินเดือน / ค่าจ้าง"),
                            ("office_supplies", "เครื่องเขียน / อุปกรณ์สำนักงาน"),
                            ("professional_fees", "ค่าที่ปรึกษา / วิชาชีพ"),
                            ("travel", "เดินทาง"),
                            ("bank_fees", "ค่าธรรมเนียมธนาคาร"),
                            ("tax_accounting", "ภาษี / บัญชี"),
                            ("hardware", "Hardware / อุปกรณ์"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=20,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="จำนวนเงิน (บาท)"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="รายละเอียด"),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ชื่อผู้ขาย/ผู้รับเงิน"
                    ),
                ),
                (
                    "is_deductible",
                    models.BooleanField(default=True, verbose_name="หักภาษีได้"),
                ),
                (
                    "tax_invoice_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="เลขที่ใบกำกับภาษี"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("transfer", "โอนเงิน"),
                            ("cash", "เงินสด"),
                            ("credit", "บัตรเครดิต"),
                            ("other", "อื่นๆ"),
                        ],
                        default="transfer",
                        max_length=10,
                        verbose_name="ช่องทางชำระ",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/%Y/%m/",
                        verbose_name="สลิป/ใบเสร็จ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="เลขที่ใบแจ้งหนี้",
                    ),
                ),
                (
                    "service_description",
                    models.TextField(blank=True, verbose_name="รายละเอียดบริการ"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดก่อนภาษี",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="VAT 7%",
                    ),
                ),
                (
                    "wht_rate",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("1", "1% (ขายสินค้า)"),
                            ("3", "3% (บริการ)"),
                            ("5", "5%"),
                            ("15", "15%"),
                        ],
                        default="3",
                        max_length=2,
                        verbose_name="อัตรา WHT",
                    ),
                ),
                (
                    "wht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="หัก ณ ที่จ่าย",
                    ),
                ),
                (
                    "total_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดที่ต้องชำระ",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่ออกใบแจ้งหนี้"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="วันครบกำหนด")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ชำระเมื่อ"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("transfer", "โอนเงิน"),
                            ("cheque", "เช็ค"),
                            ("cash", "เงินสด"),
                            ("other", "อื่นๆ"),
                        ],
                        default="transfer",
                        max_length=10,
                        verbose_name="ช่องทางชำระ",
                    ),
                ),
                (
                    "withholding_cert_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="เลขที่ใบหัก ณ ที่จ่าย"
                    ),
                ),
                (
                    "is_vat_registered",
                    models.BooleanField(default=True, verbose_name="ลูกค้าจด VAT"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="crm.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
            },
        ),
    ]
