# Generated by Django 6.0.5 on 2026-05-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อ-สกุล")),
                ("email", models.EmailField(max_length=254, verbose_name="อีเมล")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="เบอร์โทร"),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=100, verbose_name="บริษัท"),
                ),
                ("message", models.TextField(verbose_name="ข้อความ")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("landing", "Landing Page"),
                            ("blog", "Blog"),
                            ("portfolio", "Portfolio"),
                            ("other", "Other"),
                        ],
                        default="landing",
                        max_length=20,
                        verbose_name="ที่มา",
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("closed_won", "Closed - Won"),
                            ("closed_lost", "Closed - Lost"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึกภายใน")),
                (
                    "consent_given",
                    models.BooleanField(default=False, verbose_name="ยินยอม PDPA"),
                ),
                (
                    "consent_text",
                    models.TextField(blank=True, verbose_name="ข้อความ consent ที่แสดง"),
                ),
                (
                    "consent_given_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ยินยอมเมื่อ"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deletable_after",
                    models.DateTimeField(blank=True, null=True, verbose_name="ลบได้หลัง"),
                ),
            ],
            options={
                "verbose_name": "Contact Lead",
                "verbose_name_plural": "Contact Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
