# Generated by Django 6.0.5 on 2026-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_contactlead_proposal_deal_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อบริการ")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "tagline",
                    models.CharField(max_length=160, verbose_name="Tagline สั้น"),
                ),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                (
                    "icon",
                    models.CharField(
                        default="bi-stars",
                        help_text="เช่น bi-robot, bi-graph-up-arrow",
                        max_length=60,
                        verbose_name="Bootstrap Icon class",
                    ),
                ),
                (
                    "price_start",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ราคาเริ่มต้น (บาท)"
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        default="เริ่มต้น",
                        help_text="เช่น 'เริ่มต้น', 'ต่อเดือน', 'ต่อโปรเจกต์'",
                        max_length=60,
                        verbose_name="Label ราคา",
                    ),
                ),
                (
                    "features",
                    models.TextField(verbose_name="Features (แต่ละบรรทัด = 1 feature)"),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="เด่น")),
                ("display_order", models.IntegerField(default=0, verbose_name="ลำดับ")),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order"],
            },
        ),
    ]
