# Generated by Django 6.0.5 on 2026-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="Unsplash หรือ CDN URL สำหรับรูปหน้าการ์ด",
                max_length=500,
                verbose_name="รูปปก (URL)",
            ),
        ),
    ]
