# Generated by Django 6.0.5 on 2026-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_service_cover_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="เช่น 20+, 3 ปี+", max_length=20, verbose_name="ตัวเลข"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="เช่น ลูกค้า SME ที่ใช้จริง",
                        max_length=60,
                        verbose_name="คำอธิบาย",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "สถิติ (About)",
                "verbose_name_plural": "สถิติ (About)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AboutValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-check-circle",
                        help_text="เช่น bi-bar-chart-line-fill, bi-building-check",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="หัวข้อ")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "ค่านิยม (About)",
                "verbose_name_plural": "ค่านิยม (About)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="dphoompat.pjs@gmail.com",
                        max_length=254,
                        verbose_name="อีเมลติดต่อ",
                    ),
                ),
                (
                    "line_id",
                    models.CharField(
                        default="@aibizthailand", max_length=100, verbose_name="LINE ID"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="เบอร์โทร"),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="จ–ศ 09:00–18:00",
                        max_length=100,
                        verbose_name="เวลาทำการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่าเว็บไซต์",
                "verbose_name_plural": "ตั้งค่าเว็บไซต์",
            },
        ),
    ]
