# Generated by Django 6.0.5 on 2026-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_aboutstat_aboutvalue_sitesetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-check-circle",
                        help_text="เช่น bi-graph-up-arrow, bi-people-fill",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="หัวข้อ")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="คำอธิบายย่อ"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "Mission Checkpoint (About)",
                "verbose_name_plural": "Mission Checkpoints (About)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AboutExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-stars",
                        help_text="เช่น bi-chat-dots-fill, bi-cpu-fill",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="ชื่อความเชี่ยวชาญ"),
                ),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="เช่น Line OA, Facebook, WhatsApp",
                        max_length=200,
                        verbose_name="Tags (คั่นด้วยจุลภาค)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "ความเชี่ยวชาญ (About)",
                "verbose_name_plural": "ความเชี่ยวชาญ (About)",
                "ordering": ["order"],
            },
        ),
    ]
