# Generated by Django 6.0.5 on 2026-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_aboutcheckpoint_aboutexpertise"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="เราเปลี่ยนธุรกิจ SME ไทย ด้วย AI ที่ใช้งานได้จริง",
                        max_length=200,
                        verbose_name="Hero Title",
                    ),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="ไม่ใช่แค่เครื่องมือ — แต่คือพาร์ทเนอร์ที่เข้าใจธุรกิจของคุณ ออกแบบระบบ AI ที่วัดผลได้ ลดต้นทุนได้จริง เริ่มได้เร็ว",
                        verbose_name="Hero Lead (ข้อความใต้ title)",
                    ),
                ),
                (
                    "mission_title",
                    models.CharField(
                        default="ทำไมต้อง AIBiz Thailand?",
                        max_length=200,
                        verbose_name="Mission Title",
                    ),
                ),
                (
                    "mission_body",
                    models.TextField(
                        default="SME ไทยส่วนใหญ่ยังขาดความรู้และทรัพยากรในการนำ AI มาใช้งานจริง เราจึงเป็นสะพานเชื่อมระหว่างเทคโนโลยี AI และธุรกิจของคุณ โดยเราไม่ได้แค่ขายโซลูชัน แต่ทำความเข้าใจ Process จริงของธุรกิจคุณก่อน แล้วออกแบบ AI ที่ตอบโจทย์จริงๆ วัดผลได้จริงๆ",
                        verbose_name="Mission Body (ย่อหน้า)",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="พร้อมเปลี่ยนธุรกิจของคุณด้วย AI หรือยัง?",
                        max_length=200,
                        verbose_name="CTA Title",
                    ),
                ),
                (
                    "cta_subtitle",
                    models.TextField(
                        default="ปรึกษาฟรี ไม่มีข้อผูกมัด เราจะช่วยวิเคราะห์ว่า AI จะช่วยธุรกิจของคุณได้อย่างไร และควรเริ่มจากตรงไหนก่อน",
                        verbose_name="CTA Subtitle",
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        default="ปรึกษาฟรีเลย",
                        max_length=60,
                        verbose_name="CTA Button Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "เนื้อหาหน้า About",
                "verbose_name_plural": "เนื้อหาหน้า About",
            },
        ),
    ]
