# Generated by Django 6.0.5 on 2026-05-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_aboutpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-question-circle",
                        help_text="เช่น bi-robot, bi-cpu, bi-shield-check",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อหัวข้อ")),
                (
                    "url",
                    models.CharField(
                        help_text="เช่น /services/ai-chatbot/ หรือ #contact-form",
                        max_length=200,
                        verbose_name="URL หรือ anchor",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "Quick Topic (Contact)",
                "verbose_name_plural": "Quick Topics (Contact)",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_hero_subtitle",
            field=models.CharField(
                default="ค้นหาคำตอบ หรือเลือกหัวข้อที่ต้องการด้านล่าง",
                max_length=200,
                verbose_name="Contact Hero Subtitle",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_hero_title",
            field=models.CharField(
                default="เราช่วยอะไรคุณได้บ้าง?",
                max_length=200,
                verbose_name="Contact Hero Title",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="email_desc",
            field=models.CharField(
                default="สอบถามรายละเอียด — ตอบกลับภายใน 24 ชั่วโมง",
                max_length=100,
                verbose_name="Email description",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="form_desc",
            field=models.CharField(
                default="แจ้งความต้องการละเอียด — ทีมงานจะโทรกลับหาคุณ",
                max_length=100,
                verbose_name="Form description",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="guarantee",
            field=models.CharField(
                default="ปรึกษาฟรี ไม่มีข้อผูกมัด", max_length=100, verbose_name="การรับประกัน"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="line_desc",
            field=models.CharField(
                default="แชทตอบเร็วที่สุด — รับคำตอบภายใน 30 นาที",
                max_length=100,
                verbose_name="LINE description",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="response_time",
            field=models.CharField(
                default="ภายใน 24 ชั่วโมง (วันทำการ)",
                max_length=100,
                verbose_name="เวลาตอบกลับ",
            ),
        ),
    ]
