# Generated by Django 6.0.5 on 2026-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_contacttopic_sitesetting_contact_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="คำถาม")),
                ("answer", models.TextField(verbose_name="คำตอบ")),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "FAQ (Home)",
                "verbose_name_plural": "FAQs (Home)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="ระบบ AI สำหรับธุรกิจ SME ไทย",
                        max_length=200,
                        verbose_name="Hero Title",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="เพิ่มรายได้ ลดต้นทุน ทำงานอัตโนมัติ",
                        verbose_name="Hero Subtitle",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        default="ปรึกษาฟรี", max_length=60, verbose_name="Hero CTA Button"
                    ),
                ),
                (
                    "hero_cta2_text",
                    models.CharField(
                        blank=True,
                        default="ดูผลงาน",
                        max_length=60,
                        verbose_name="Hero CTA 2 Button",
                    ),
                ),
                (
                    "pain_title",
                    models.CharField(
                        default="ปัญหาที่ SME ไทยเจอบ่อย",
                        max_length=200,
                        verbose_name="Pain Section Title",
                    ),
                ),
                (
                    "pain_subtitle",
                    models.TextField(blank=True, verbose_name="Pain Section Subtitle"),
                ),
                (
                    "process_title",
                    models.CharField(
                        default="เราทำงานอย่างไร",
                        max_length=200,
                        verbose_name="Process Section Title",
                    ),
                ),
                (
                    "process_subtitle",
                    models.TextField(
                        blank=True, verbose_name="Process Section Subtitle"
                    ),
                ),
                (
                    "testi_title",
                    models.CharField(
                        default="ลูกค้าพูดถึงเรา",
                        max_length=200,
                        verbose_name="Testimonial Section Title",
                    ),
                ),
                (
                    "faq_title",
                    models.CharField(
                        default="คำถามที่พบบ่อย",
                        max_length=200,
                        verbose_name="FAQ Section Title",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="พร้อมเริ่มต้นแล้วหรือยัง?",
                        max_length=200,
                        verbose_name="CTA Title",
                    ),
                ),
                (
                    "cta_subtitle",
                    models.TextField(
                        default="ปรึกษาฟรี ไม่มีข้อผูกมัด", verbose_name="CTA Subtitle"
                    ),
                ),
                (
                    "cta_button",
                    models.CharField(
                        default="ปรึกษาฟรีเลย",
                        max_length=60,
                        verbose_name="CTA Button Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "เนื้อหาหน้าแรก (Home)",
                "verbose_name_plural": "เนื้อหาหน้าแรก (Home)",
            },
        ),
        migrations.CreateModel(
            name="HomePain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-exclamation-circle",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="หัวข้อ")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "Pain Point (Home)",
                "verbose_name_plural": "Pain Points (Home)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomeProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_num",
                    models.CharField(
                        default="01", max_length=10, verbose_name="เลข Step"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="หัวข้อ")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="bi-check-circle",
                        max_length=60,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "Process Step (Home)",
                "verbose_name_plural": "Process Steps (Home)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomeTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(verbose_name="คำพูด")),
                ("author", models.CharField(max_length=100, verbose_name="ชื่อ")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="ตำแหน่ง/บริษัท"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="Avatar URL")),
                ("order", models.IntegerField(default=0, verbose_name="ลำดับ")),
            ],
            options={
                "verbose_name": "Testimonial (Home)",
                "verbose_name_plural": "Testimonials (Home)",
                "ordering": ["order"],
            },
        ),
    ]
