# Generated by Django 6.0.5 on 2026-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_homefaq_homepage_homepain_homeprocess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("product", "ผลิตภัณฑ์ — deploy ซ้ำได้"),
                    ("custom", "งานรับทำ — ทำจบเป็นชิ้น"),
                ],
                default="custom",
                help_text="ใช้แบ่งกลุ่มในหน้า Project Monitor — ผลิตภัณฑ์มีเครื่องรันให้เฝ้า งานรับทำไม่มี",
                max_length=10,
                verbose_name="ประเภทการส่งมอบ",
            ),
        ),
    ]
