# Generated by Django 6.0.5 on 2026-08-28 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_service_delivery_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlead",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="มีค่าเมื่อบันทึกเองจากหลังบ้าน · ว่าง = มาจากฟอร์มบนเว็บ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้บันทึก",
            ),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="is_spam",
            field=models.BooleanField(
                default=False,
                help_text="ทำเครื่องหมายแทนการลบ เก็บไว้ดูรูปแบบบอทได้",
                verbose_name="เป็นสแปม",
            ),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="last_contacted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="คุยครั้งล่าสุดเมื่อ"
            ),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="next_follow_up",
            field=models.DateField(
                blank=True,
                help_text="เว้นว่าง = ไม่มีอะไรทวง lead รายนี้จะเงียบหายไปเอง",
                null=True,
                verbose_name="ตามอีกครั้งวันที่",
            ),
        ),
        migrations.AddField(
            model_name="contactlead",
            name="spam_marked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ทำเครื่องหมายสแปมเมื่อ"
            ),
        ),
        migrations.AlterField(
            model_name="contactlead",
            name="source",
            field=models.CharField(
                choices=[
                    ("landing", "Landing Page"),
                    ("blog", "Blog"),
                    ("portfolio", "Portfolio"),
                    ("linkedin", "LinkedIn"),
                    ("line_oa", "LINE OA"),
                    ("fb_group", "Facebook Group"),
                    ("youtube", "YouTube"),
                    ("tiktok", "TikTok"),
                    ("referral", "คนแนะนำต่อ"),
                    ("cold_dm", "ทัก DM เอง"),
                    ("google_ads", "Google Ads"),
                    ("other", "Other"),
                ],
                default="landing",
                max_length=20,
                verbose_name="ที่มา",
            ),
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("call", "โทรคุย"),
                            ("line", "คุยทาง LINE"),
                            ("email", "อีเมล"),
                            ("meeting", "นัดเจอ / ประชุม"),
                            ("quote", "ส่งใบเสนอราคา"),
                            ("note", "บันทึกภายใน"),
                        ],
                        default="call",
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                ("note", models.TextField(verbose_name="คุยอะไร")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เกิดขึ้นเมื่อ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บันทึก",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="pages.contactlead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกการติดต่อ Lead",
                "verbose_name_plural": "บันทึกการติดต่อ Lead",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
