# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0004_category_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อ Campaign")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("line", "LINE"),
                            ("email", "Email"),
                            ("google", "Google Ads"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("organic", "Organic"),
                            ("blog", "Blog"),
                            ("youtube", "YouTube"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=15,
                        verbose_name="ช่องทาง",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="งบประมาณ (บาท)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="วันเริ่ม")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="วันสิ้นสุด"),
                ),
                ("kpi_leads", models.IntegerField(default=0, verbose_name="เป้า Leads")),
                (
                    "actual_leads",
                    models.IntegerField(default=0, verbose_name="Leads จริง"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ContentCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="หัวข้อ (ถ้ายังไม่มีบทความ)"
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="วันเผยแพร่ที่กำหนด")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("blog", "Blog"),
                            ("line", "LINE"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("other", "อื่นๆ"),
                        ],
                        default="blog",
                        max_length=10,
                        verbose_name="ช่องทาง",
                    ),
                ),
                (
                    "assigned_agent",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Agent รับผิดชอบ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("briefed", "Briefed"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="idea",
                        max_length=15,
                        verbose_name="สถานะ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_slots",
                        to="blog.article",
                        verbose_name="บทความ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Calendar",
                "verbose_name_plural": "Content Calendar",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200, verbose_name="Keyword")),
                (
                    "search_volume",
                    models.IntegerField(default=0, verbose_name="Search Volume/เดือน"),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=0, verbose_name="Keyword Difficulty (0-100)"
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("info", "Informational (ข้อมูล)"),
                            ("trans", "Transactional (ซื้อ)"),
                            ("nav", "Navigational (หาเว็บ)"),
                            ("commercial", "Commercial (เปรียบเทียบ/ราคา)"),
                        ],
                        default="info",
                        max_length=15,
                        verbose_name="Search Intent",
                    ),
                ),
                (
                    "current_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Rank ปัจจุบัน"
                    ),
                ),
                (
                    "target_position",
                    models.IntegerField(blank=True, null=True, verbose_name="เป้า Rank"),
                ),
                (
                    "last_checked_date",
                    models.DateField(blank=True, null=True, verbose_name="ตรวจสอบล่าสุด"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก / Brief")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keywords",
                        to="blog.article",
                        verbose_name="บทความที่ target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
                "ordering": ["current_rank"],
            },
        ),
    ]
