# Generated by Django 6.0.5 on 2026-05-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentCalendar",
        ),
    ]
