# Generated by Django 6.0.5 on 2026-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_delete_contentcalendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBacklog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="ลำดับ")),
                ("topic", models.CharField(max_length=400, verbose_name="หัวข้อ")),
                (
                    "keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Target Keyword"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1 — High"),
                            ("P2", "P2 — Medium"),
                            ("P3", "P3 — Low"),
                        ],
                        default="P1",
                        max_length=2,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "owner",
                    models.CharField(
                        blank=True, default="All", max_length=100, verbose_name="Owner"
                    ),
                ),
                (
                    "added_by",
                    models.CharField(blank=True, max_length=100, verbose_name="เพิ่มโดย"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Content Backlog",
                "verbose_name_plural": "Content Backlog",
                "ordering": ["num"],
            },
        ),
    ]
