# Generated by Django 6.0.5 on 2026-05-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_backlog_ref_alter_article_status"),
        ("marketing", "0003_contentbacklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbacklog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backlog_items",
                to="blog.category",
                verbose_name="หมวดหมู่บทความ",
            ),
        ),
    ]
