# Generated by Django 6.0.5 on 2026-05-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_add_article_fk_to_calendar_event"),
        ("marketing", "0004_contentbacklog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbacklog",
            name="calendar_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backlog_item",
                to="dashboard.calendarevent",
                verbose_name="Calendar Event",
            ),
        ),
    ]
