# Generated by Django 6.0.5 on 2026-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0005_add_calendar_event_fk_to_backlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbacklog",
            name="assigned_agent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content-writer-th", "Content Writer TH (ทั่วไป)"),
                    ("healthcare-writer", "Healthcare Writer (คลินิก/โรงพยาบาล)"),
                    ("ecommerce-writer", "E-commerce Writer (ร้านค้าออนไลน์)"),
                    ("hospitality-writer", "Hospitality Writer (โรงแรม/รีสอร์ท)"),
                    ("beauty-wellness-writer", "Beauty & Wellness Writer (สปา/นวด)"),
                    ("hr-education-writer", "HR & Education Writer (HR/โรงเรียน)"),
                    ("creator-coach-writer", "Creator & Coach Writer (โค้ช/ครีเอเตอร์)"),
                    ("ai-news-scout", "AI News Scout (ข่าว AI)"),
                    ("marketing-specialist", "Marketing Specialist"),
                    ("seo-specialist", "SEO Specialist"),
                ],
                default="content-writer-th",
                max_length=50,
                verbose_name="ผู้รับงาน (Agent)",
            ),
        ),
    ]
