# Generated by Django 6.0.5 on 2026-05-21 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0006_add_assigned_agent_to_backlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbacklog",
            name="writer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backlog_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="นักเขียน",
            ),
        ),
        migrations.AlterField(
            model_name="contentbacklog",
            name="assigned_agent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content-writer-th", "Content Writer TH (ทั่วไป)"),
                    ("healthcare-writer", "Healthcare Writer (คลินิก/โรงพยาบาล)"),
                    ("ecommerce-writer", "E-commerce Writer (ร้านค้าออนไลน์)"),
                    ("hospitality-writer", "Hospitality Writer (โรงแรม/รีสอร์ท)"),
                    ("beauty-wellness-writer", "Beauty & Wellness Writer (สปา/นวด)"),
                    ("hr-education-writer", "HR & Education Writer (HR/โรงเรียน)"),
                    ("creator-coach-writer", "Creator & Coach Writer (โค้ช/ครีเอเตอร์)"),
                    ("ai-news-scout", "AI News Scout (ข่าว AI)"),
                    ("marketing-specialist", "Marketing Specialist"),
                    ("seo-specialist", "SEO Specialist"),
                ],
                default="content-writer-th",
                max_length=50,
                verbose_name="AI ส่งงาน",
            ),
        ),
    ]
