# Generated by Django 6.0.5 on 2026-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0007_add_writer_to_backlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="เช่น beauty_wellness — script ใช้ค่านี้เรียก",
                        unique=True,
                        verbose_name="รหัส segment",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อกลุ่ม")),
                (
                    "agent_slug",
                    models.CharField(
                        help_text="slug ใน frontmatter ของไฟล์ agent",
                        max_length=60,
                        verbose_name="agent ที่รับผิดชอบ",
                    ),
                ),
                (
                    "pen_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="นามปากกา"
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="สรรพนามในบทความ"
                    ),
                ),
                (
                    "tone",
                    models.TextField(
                        help_text="สรุปสั้น ๆ ว่าเขียนด้วยน้ำเสียงแบบไหน",
                        verbose_name="โทนการเขียน",
                    ),
                ),
                ("reader", models.TextField(blank=True, verbose_name="ผู้อ่านเป็นใคร")),
                (
                    "research",
                    models.TextField(
                        blank=True,
                        help_text="หนึ่งบรรทัดต่อหนึ่งแหล่ง",
                        verbose_name="แหล่งค้นข้อมูลและมุมที่ควรหา",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("rounded", "มุมโค้ง (อบอุ่น เป็นมิตร)"),
                            ("soft", "มุมมนน้อย (กลาง ๆ)"),
                            ("sharp", "มุมเหลี่ยม (จริงจัง เป็นทางการ)"),
                        ],
                        default="soft",
                        max_length=15,
                        verbose_name="รูปทรง",
                    ),
                ),
                (
                    "accent_secondary",
                    models.CharField(
                        default="#C9A84C",
                        help_text="สีหลักกรม+ทองห้ามเปลี่ยน อันนี้คือสีรองเท่านั้น",
                        max_length=7,
                        verbose_name="สีรอง (hex)",
                    ),
                ),
                (
                    "icon_mood",
                    models.CharField(
                        choices=[
                            ("soft", "นุ่มนวล"),
                            ("clean", "เรียบ สะอาด"),
                            ("technical", "เทคนิค"),
                            ("energetic", "มีพลัง"),
                        ],
                        default="clean",
                        max_length=15,
                        verbose_name="อารมณ์ไอคอน",
                    ),
                ),
                (
                    "prefer_diagram",
                    models.CharField(
                        choices=[
                            ("concept", "แผนภาพแนวคิด"),
                            ("steps", "ขั้นตอนเป็นลำดับ"),
                            ("comparison", "ตารางเปรียบเทียบ"),
                            ("stats", "ตัวเลขและสถิติ"),
                        ],
                        default="concept",
                        max_length=15,
                        verbose_name="ชนิด diagram ที่กลุ่มนี้ชอบ",
                    ),
                ),
                (
                    "cover_pose",
                    models.CharField(
                        choices=[
                            ("thinking", "คิด"),
                            ("pointing", "ชี้"),
                            ("happy", "ยิ้มสดใส"),
                            ("serious", "จริงจัง"),
                            ("reading", "อ่าน"),
                        ],
                        default="thinking",
                        max_length=15,
                        verbose_name="ท่าของหนูดี",
                    ),
                ),
                (
                    "cover_mood",
                    models.CharField(
                        choices=[
                            ("tech", "เทคโนโลยี"),
                            ("warm", "อบอุ่น"),
                            ("clean", "สะอาดตา"),
                            ("dark", "เข้ม"),
                        ],
                        default="clean",
                        max_length=15,
                        verbose_name="อารมณ์พื้นหลัง",
                    ),
                ),
                (
                    "hook_style",
                    models.CharField(
                        blank=True,
                        help_text="เช่น คำถามที่ relate ได้ / ตัวเลขที่น่าตกใจ",
                        max_length=200,
                        verbose_name="รูปแบบ hook",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ใช้งานอยู่"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึกเพิ่มเติม")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Segment Profile",
                "verbose_name_plural": "Segment Profiles",
                "ordering": ["name"],
            },
        ),
    ]
