# Generated by Django 6.0.5 on 2026-08-26 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_article_content_format_article_content_md"),
        ("marketing", "0008_segmentprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlopPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="ข้อความที่ค้นหาตรง ๆ ในบทความ",
                        max_length=200,
                        verbose_name="คำ/วลีที่จับ",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("word", "คำต้องห้าม"),
                            ("phrase", "วลีสำเร็จรูป"),
                            ("structure", "รูปประโยค/โครงสร้าง"),
                            ("claim", "การอ้างลอย ๆ"),
                        ],
                        default="phrase",
                        max_length=15,
                        verbose_name="ชนิด",
                    ),
                ),
                (
                    "penalty",
                    models.IntegerField(
                        choices=[
                            (3, "เบา (-3)"),
                            (5, "กลาง (-5)"),
                            (8, "หนัก (-8)"),
                            (10, "ร้ายแรง (-10)"),
                        ],
                        default=5,
                        verbose_name="คะแนนที่หัก",
                    ),
                ),
                (
                    "why",
                    models.TextField(
                        help_text="อธิบายให้นักเขียนเข้าใจ ไม่ใช่แค่บอกว่าห้าม",
                        verbose_name="ทำไมถึงไม่ดี",
                    ),
                ),
                (
                    "fix",
                    models.TextField(blank=True, verbose_name="ควรเขียนแทนว่าอย่างไร"),
                ),
                (
                    "example_bad",
                    models.TextField(blank=True, verbose_name="ตัวอย่างที่ไม่ดี"),
                ),
                (
                    "example_ok",
                    models.TextField(blank=True, verbose_name="ตัวอย่างที่แก้แล้ว"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ใช้งานอยู่"),
                ),
                (
                    "hit_count",
                    models.IntegerField(
                        default=0,
                        help_text="ระบบนับให้เอง ใช้ดูว่าอันไหนเป็นปัญหาจริง",
                        verbose_name="เจอมาแล้วกี่ครั้ง",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI-Slop Pattern",
                "verbose_name_plural": "AI-Slop Patterns (ไทย)",
                "ordering": ["-penalty", "pattern"],
            },
        ),
        migrations.CreateModel(
            name="ContentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rubric",
                    models.CharField(
                        default="content-quality", max_length=30, verbose_name="เกณฑ์ที่ใช้"
                    ),
                ),
                (
                    "aggregate",
                    models.IntegerField(
                        default=0, verbose_name="คะแนนรวม (ถ่วงน้ำหนักแล้ว)"
                    ),
                ),
                ("rounds", models.IntegerField(default=0, verbose_name="จำนวนรอบที่วน")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "กำลังให้คะแนน"),
                            ("passed", "ผ่าน (90+)"),
                            ("needs_work", "ยังไม่ผ่าน"),
                        ],
                        default="running",
                        max_length=15,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "panel",
                    models.TextField(
                        blank=True,
                        help_text="หนึ่งบรรทัดต่อหนึ่งคน",
                        verbose_name="รายชื่อคณะกรรมการ",
                    ),
                ),
                (
                    "weaknesses",
                    models.TextField(blank=True, verbose_name="จุดอ่อนที่เหลืออยู่"),
                ),
                (
                    "slop_hits",
                    models.TextField(blank=True, verbose_name="AI-slop ที่เจอ"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="อนุมัติเมื่อ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้อนุมัติ",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="blog.article",
                        verbose_name="บทความ",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scores",
                        to="marketing.segmentprofile",
                        verbose_name="กลุ่มลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Score",
                "verbose_name_plural": "Content Scores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpertScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_no", models.IntegerField(default=1, verbose_name="รอบที่")),
                ("expert", models.CharField(max_length=100, verbose_name="ผู้เชี่ยวชาญ")),
                (
                    "lens",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="มองจากมุมไหน"
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="คะแนน 0-100")),
                ("weight", models.FloatField(default=1.0, verbose_name="น้ำหนัก")),
                ("feedback", models.TextField(blank=True, verbose_name="เหตุผล")),
                (
                    "content_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_scores",
                        to="marketing.contentscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expert Score",
                "verbose_name_plural": "Expert Scores",
                "ordering": ["round_no", "-weight", "expert"],
            },
        ),
    ]
