# Generated by Django 6.0.5 on 2026-05-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                ("start_datetime", models.DateTimeField(verbose_name="วันเริ่ม")),
                (
                    "end_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันสิ้นสุด"),
                ),
                ("all_day", models.BooleanField(default=True, verbose_name="ทั้งวัน")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "ทั่วไป"),
                            ("priority", "งานสำคัญ"),
                            ("meeting", "ประชุม"),
                            ("delivery", "ส่งมอบงาน"),
                            ("personal", "ส่วนตัว"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="ประเภท",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="รายละเอียด")),
                ("color", models.CharField(blank=True, max_length=7, verbose_name="สี")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="event ระบบ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "ordering": ["start_datetime"],
            },
        ),
    ]
