# Generated by Django 6.0.5 on 2026-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "ทั่วไป"),
                    ("priority", "งานสำคัญ"),
                    ("meeting", "ประชุม"),
                    ("delivery", "ส่งมอบงาน"),
                    ("personal", "ส่วนตัว"),
                    ("milestone", "Milestone / แผน"),
                    ("action", "งานต้องทำ (Task)"),
                    ("recurring", "Recurring / นัดประจำ"),
                    ("content_plan", "Content Plan"),
                    ("backlog", "Content Backlog"),
                ],
                default="general",
                max_length=50,
                verbose_name="ประเภท",
            ),
        ),
    ]
