# Generated by Django 6.0.5 on 2026-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_calendarevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="เสร็จแล้ว"),
        ),
    ]
