# Generated by Django 6.0.5 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_add_is_completed_to_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="assigned_to",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="ผู้ทำงาน"
            ),
        ),
    ]
