# Generated by Django 6.0.5 on 2026-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_add_assigned_to_calendarevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStandup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        choices=[
                            ("chief-of-staff", "Chief of Staff"),
                            ("hustler-sales", "Hustler (Sales)"),
                            ("ai-orchestrator", "AI Orchestrator"),
                            ("money-manager", "Money Manager"),
                            ("ai-toolsmith", "AI Toolsmith"),
                            ("qa-agent", "QA Agent"),
                            ("marketing-specialist", "Marketing Specialist"),
                            ("customer-success", "Customer Success"),
                            ("data-analyst", "Data Analyst"),
                            ("legal-advisor", "Legal Advisor"),
                            ("seo-specialist", "SEO Specialist"),
                            ("content-writer-th", "Content Writer (TH)"),
                            ("frontend-designer", "Frontend Designer"),
                        ],
                        max_length=30,
                        verbose_name="Agent",
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                ("yesterday", models.TextField(verbose_name="ทำอะไรเมื่อวาน")),
                ("today", models.TextField(verbose_name="วันนี้จะทำอะไร")),
                (
                    "blocker",
                    models.TextField(blank=True, verbose_name="Blocker / อุปสรรค"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Standup",
                "verbose_name_plural": "Team Standups",
                "ordering": ["-date", "agent_name"],
                "unique_together": {("agent_name", "date")},
            },
        ),
    ]
