# Generated by Django 6.0.5 on 2026-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_teamstandup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                ("content", models.TextField(blank=True, verbose_name="เนื้อหา")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                        ],
                        default="gold",
                        max_length=10,
                        verbose_name="สี",
                    ),
                ),
                ("pinned", models.BooleanField(default=False, verbose_name="ปักหมุด")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-pinned", "-updated_at"],
            },
        ),
    ]
