# Generated by Django 6.0.5 on 2026-05-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamStandup",
        ),
    ]
