# Generated by Django 6.0.5 on 2026-05-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_delete_teamstandup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "ทั่วไป"),
                    ("action", "งานต้องทำ"),
                    ("delivery", "ส่งมอบงาน"),
                    ("personal", "ส่วนตัว"),
                    ("plan", "แผน"),
                    ("article", "บทความ"),
                ],
                default="general",
                max_length=50,
                verbose_name="ประเภท",
            ),
        ),
    ]
