# Generated by Django 6.0.5 on 2026-05-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_backlog_ref_alter_article_status"),
        ("dashboard", "0008_alter_calendarevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_events",
                to="blog.article",
                verbose_name="บทความ",
            ),
        ),
    ]
