# Generated by Django 6.0.5 on 2026-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="ใส่ URL รูปจาก Unsplash หรือ CDN ภายนอก — ใช้แทนการอัพโหลดไฟล์ ถ้ากรอกทั้งคู่จะใช้ URL นี้",
                max_length=500,
                verbose_name="รูปปก (URL ภายนอก)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/covers/%Y/%m/",
                verbose_name="รูปปก (อัพโหลด)",
            ),
        ),
    ]
