# Generated by Django 6.0.5 on 2026-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_cover_image_url_alter_article_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "Primary (น้ำเงิน)"),
                    ("secondary", "Secondary (เทา)"),
                    ("success", "Success (เขียว)"),
                    ("danger", "Danger (แดง)"),
                    ("warning", "Warning (เหลือง)"),
                    ("info", "Info (ฟ้า)"),
                    ("dark", "Dark (ดำ)"),
                ],
                default="secondary",
                max_length=20,
                verbose_name="สี Badge",
            ),
        ),
    ]
