# Generated by Django 6.0.5 on 2026-05-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_color"),
        ("marketing", "0003_contentbacklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="backlog_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="marketing.contentbacklog",
                verbose_name="มาจาก Backlog",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "รอเขียน"),
                    ("draft", "Draft"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
