# Generated by Django 6.0.5 on 2026-06-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_backlog_ref_alter_article_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="layout",
            field=models.CharField(
                choices=[("article", "บทความปกติ"), ("docs", "คู่มือ / Docs")],
                default="article",
                help_text="'คู่มือ / Docs' = แสดงสารบัญอัตโนมัติ + สไตล์ docs (callout/step) + ซ่อน CTA ขายของ",
                max_length=20,
                verbose_name="รูปแบบหน้า",
            ),
        ),
    ]
