# Generated by Django 6.0.5 on 2026-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_article_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("html", "HTML (เขียนใน CKEditor)"),
                    ("markdown", "Markdown (เขียนใน ช่องเนื้อหา Markdown)"),
                ],
                default="html",
                help_text="เลือก Markdown สำหรับบทเรียน/คู่มือ ที่ต้องใช้ callout, step, code block, SVG — CKEditor จะลบแท็กพวกนี้ทิ้ง",
                max_length=20,
                verbose_name="รูปแบบการเขียน",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="content_md",
            field=models.TextField(
                blank=True,
                help_text="ใช้เมื่อรูปแบบการเขียน = Markdown เท่านั้น ระบบจะแปลงเป็น HTML ลงช่อง 'เนื้อหา' ให้อัตโนมัติทุกครั้งที่เซฟ",
                verbose_name="เนื้อหา (Markdown)",
            ),
        ),
    ]
