# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0002_contactlead_proposal_deal_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="ชื่อบริษัท"),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="อุตสาหกรรม"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("A", "A — Enterprise"),
                            ("B", "B — Mid-Market"),
                            ("C", "C — SME"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="Tier",
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="มูลค่าสัญญา (บาท)",
                    ),
                ),
                (
                    "health_score",
                    models.IntegerField(
                        default=80, verbose_name="Health Score (0-100)"
                    ),
                ),
                (
                    "nps_score",
                    models.IntegerField(default=0, verbose_name="NPS Score (-100-100)"),
                ),
                (
                    "contract_start",
                    models.DateField(blank=True, null=True, verbose_name="วันเริ่มสัญญา"),
                ),
                (
                    "contract_end",
                    models.DateField(blank=True, null=True, verbose_name="วันหมดสัญญา"),
                ),
                (
                    "account_owner",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ผู้ดูแลบัญชี"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="เลขที่ใบเสนอราคา",
                    ),
                ),
                (
                    "items",
                    models.JSONField(default=list, verbose_name="รายการสินค้า/บริการ"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดรวมก่อนภาษี",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดรวมทั้งหมด",
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="ใบเสนอราคาหมดอายุ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "discount_authority",
                    models.BooleanField(
                        default=False, verbose_name="ต้องขออนุมัติส่วนลด (>10%)"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="อนุมัติโดย"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="pages.contactlead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Renewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renewal_date", models.DateField(verbose_name="วันต่อสัญญา")),
                (
                    "mrr_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="MRR (บาท)",
                    ),
                ),
                (
                    "prev_mrr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="MRR เดิม (บาท)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("contacted", "Contacted"),
                            ("negotiating", "Negotiating"),
                            ("renewed", "Renewed"),
                            ("at_risk", "At Risk"),
                            ("churned", "Churned"),
                            ("auto_renewed", "Auto-Renewed"),
                        ],
                        default="upcoming",
                        max_length=15,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ผู้รับผิดชอบ"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ส่ง Reminder เมื่อ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="crm.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "Renewal",
                "verbose_name_plural": "Renewals",
                "ordering": ["renewal_date"],
            },
        ),
    ]
