# Generated by Django 6.0.5 on 2026-05-08 11:10

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_title",
                    models.CharField(max_length=200, verbose_name="ชื่อโปรเจกต์"),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="เว้นว่างได้ถ้าลูกค้าไม่ให้เปิดเผย",
                        max_length=200,
                        verbose_name="ชื่อลูกค้า",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("ecommerce", "ร้านค้า / E-Commerce"),
                            ("clinic", "คลินิก / โรงพยาบาล"),
                            ("hotel", "โรงแรม / รีสอร์ท"),
                            ("b2b", "B2B / Lead Gen"),
                            ("factory", "โรงงาน / โลจิสติกส์"),
                            ("internal", "ทีมงานภายในองค์กร"),
                            ("legal_finance", "กฎหมาย / การเงิน"),
                            ("education", "โรงเรียน / สถาบัน"),
                            ("other", "อื่น ๆ"),
                        ],
                        max_length=30,
                        verbose_name="อุตสาหกรรม",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/covers/%Y/%m/",
                        verbose_name="รูปปก",
                    ),
                ),
                ("problem", models.TextField(verbose_name="ปัญหาเดิม")),
                (
                    "solution",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="วิธีแก้"),
                ),
                ("result", models.TextField(verbose_name="ผลลัพธ์")),
                (
                    "roi_metric",
                    models.CharField(
                        blank=True,
                        help_text="เช่น 'ลด workload 70%' หรือ 'เพิ่ม conversion 3 เท่า'",
                        max_length=120,
                        verbose_name="ROI เด่น",
                    ),
                ),
                (
                    "testimonial",
                    models.TextField(blank=True, verbose_name="Testimonial"),
                ),
                (
                    "testimonial_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ผู้พูด (ชื่อ + ตำแหน่ง)"
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="เช่น 'LINE Messaging API, Claude, Django'",
                        max_length=200,
                        verbose_name="Tech stack",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="เช่น '2 สัปดาห์'",
                        max_length=50,
                        verbose_name="ระยะเวลา",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="โชว์หน้าแรก"),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Case Studies",
                "ordering": ["display_order", "-published_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="portfolio_c_status_eaa7a3_idx",
                    ),
                    models.Index(fields=["slug"], name="portfolio_c_slug_1f2557_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaseStudyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "case_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.casestudy",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
