# Generated by Django 6.0.5 on 2026-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                help_text="ใส่ URL จาก Unsplash หรือ CDN — ถ้ากรอกทั้งคู่จะใช้ URL นี้",
                max_length=500,
                verbose_name="รูปปก (URL ภายนอก)",
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/covers/%Y/%m/",
                verbose_name="รูปปก (อัพโหลด)",
            ),
        ),
    ]
