# -*- coding: utf-8 -*-
"""
Auto-generate diagrams for article:
  Title : คู่แข่งใช้ AI แล้ว ตอนนี้คุณยังไม่ใช้ กำลังแพ้อยู่โดยไม่รู้ตัว
  Keyword slug : competitor-ai-sme-thai
  Article ID   : 8
  Sections     : 7 H2
Generated by auto-diagram-generator skill | Graphic Designer Agent
"""

from PIL import Image, ImageDraw, ImageFont
import os

# ─── CONFIG ───────────────────────────────────────────────────────────────────
OUT_DIR   = r"E:\Project Peyo Peyo\Agent Skill Claude\scripts\article_assets"
W, H      = 800, 500
BG        = "#0F172A"   # Navy dark
GOLD      = "#C9A84C"   # Gold accent
WHITE     = "#FFFFFF"
GRAY_TEXT = "#94A3B8"   # Slate-400
DARK_CARD = "#1E293B"   # Slate-800
GREEN     = "#22C55E"   # success
RED_SOFT  = "#EF4444"   # danger

FONT_PATH      = "C:/Windows/Fonts/LeelawUI.ttf"
FONT_PATH_BOLD = "C:/Windows/Fonts/LeelawUI.ttf"  # ใช้ size ใหญ่แทน bold

os.makedirs(OUT_DIR, exist_ok=True)

# ─── HELPERS ──────────────────────────────────────────────────────────────────

def make_canvas():
    img  = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)
    return img, draw

def font(size):
    return ImageFont.truetype(FONT_PATH, size)

def save_webp(img, filename):
    path = os.path.join(OUT_DIR, filename)
    img.save(path, "WEBP", quality=82, method=6)
    kb = os.path.getsize(path) / 1024
    print(f"  saved {filename}  ({kb:.1f} KB)")
    return path

def draw_header(draw, title, subtitle=""):
    """Gold top-bar + white title"""
    draw.rectangle([0, 0, W, 6], fill=GOLD)
    draw.text((40, 28), title, font=font(22), fill=GOLD)
    if subtitle:
        draw.text((40, 58), subtitle, font=font(14), fill=GRAY_TEXT)

def draw_footer(draw):
    draw.rectangle([0, H-36, W, H], fill=DARK_CARD)
    draw.text((40, H-26), "Noodee BootBiz  |  noodeebootbiz.com", font=font(12), fill=GRAY_TEXT)

def wrap_text(draw, text, x, y, max_width, fnt, fill=WHITE, line_height=None):
    """Word-wrap text in a box."""
    if line_height is None:
        line_height = fnt.size + 6
    words = text.split()
    line  = ""
    cy    = y
    for w in words:
        test = line + w + " "
        bbox = draw.textbbox((0, 0), test, font=fnt)
        if bbox[2] - bbox[0] > max_width and line:
            draw.text((x, cy), line.strip(), font=fnt, fill=fill)
            cy   += line_height
            line  = w + " "
        else:
            line = test
    if line:
        draw.text((x, cy), line.strip(), font=fnt, fill=fill)
    return cy + line_height

# ─── DIAGRAM 01 — COMPARISON (คู่แข่ง vs คุณ) ────────────────────────────────

def gen_01():
    img, draw = make_canvas()
    draw_header(draw, "Section 01 — คู่แข่งกำลังทำอะไร ในขณะที่คุณยังทำแบบเดิม", "Comparison Diagram")

    left_items = [
        "ตอบลูกค้าด้วย AI 24 ชม.",
        "วิเคราะห์ยอดขายแบบ Real-time",
        "ส่งโปรโมชันแบบ Personalized",
        "ลดต้นทุนงานซ้ำซาก 40%",
        "ขยายทีมโดยไม่เพิ่มพนักงาน",
    ]
    right_items = [
        "ตอบลูกค้าด้วยคน — ช้า + พลาด",
        "ดูรายงานสิ้นเดือนอย่างเดียว",
        "ส่งโปรโมชันแบบ Blast ทั่วไป",
        "จ่ายค่าแรงงาน Manual 100%",
        "จ้างคนเพิ่มทุกครั้งที่ขยาย",
    ]

    col_w = 310
    row_h = 52
    top_y = 100

    # Column headers
    draw.rectangle([30, top_y, 30+col_w, top_y+38], fill=GOLD)
    draw.text((30 + col_w//2, top_y+9), "คู่แข่งที่ใช้ AI", font=font(16), fill=BG,
              anchor="mm")

    draw.rectangle([W-30-col_w, top_y, W-30, top_y+38], fill=RED_SOFT)
    draw.text((W-30-col_w//2, top_y+9), "ธุรกิจที่ยังไม่ใช้ AI", font=font(16), fill=WHITE,
              anchor="mm")

    # VS badge centre
    draw.ellipse([W//2-24, top_y+4, W//2+24, top_y+34], fill=DARK_CARD, outline=GOLD, width=2)
    draw.text((W//2, top_y+10), "VS", font=font(15), fill=GOLD, anchor="mm")

    # Rows
    for i, (l, r) in enumerate(zip(left_items, right_items)):
        y = top_y + 48 + i * row_h
        bg_row = DARK_CARD if i % 2 == 0 else BG
        draw.rectangle([30, y, 30+col_w, y+row_h-4], fill=bg_row)
        draw.rectangle([W-30-col_w, y, W-30, y+row_h-4], fill=bg_row)

        # check / cross icon text
        draw.text((36, y+14), "✓", font=font(16), fill=GREEN)
        draw.text((50, y+14), l, font=font(14), fill=WHITE)

        draw.text((W-30-col_w+6, y+14), "✗", font=font(16), fill=RED_SOFT)
        draw.text((W-30-col_w+22, y+14), r, font=font(14), fill=GRAY_TEXT)

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-01-comparison.webp")

# ─── DIAGRAM 02 — STATS (5 สัญญาณ) ───────────────────────────────────────────

def gen_02():
    img, draw = make_canvas()
    draw_header(draw, "Section 02 — 5 สัญญาณที่บอกว่าธุรกิจคุณกำลังตกขบวน AI", "Warning Signs")

    signs = [
        ("01", "ลูกค้าหาย", "ลูกค้าเริ่มไปใช้คู่แข่งที่ตอบเร็วกว่า"),
        ("02", "งานซ้ำเยอะ", "พนักงานทำงาน Manual เกิน 50% ของเวลา"),
        ("03", "ข้อมูลกระจัดกระจาย", "ไม่มีระบบรวม data ตัดสินใจด้วยความรู้สึก"),
        ("04", "ต้นทุนสูงขึ้น", "ต้องจ้างคนเพิ่มทุกครั้งที่ยอดขายเพิ่ม"),
        ("05", "ปรับตัวช้า", "คู่แข่งออก campaign ใหม่ คุณยังวางแผนอยู่"),
    ]

    card_w, card_h = 140, 165
    gap    = 14
    total  = len(signs) * card_w + (len(signs)-1) * gap
    start_x = (W - total) // 2
    top_y  = 110

    for i, (num, title, desc) in enumerate(signs):
        x = start_x + i * (card_w + gap)
        draw.rectangle([x, top_y, x+card_w, top_y+card_h], fill=DARK_CARD, outline=GOLD, width=2)

        # number badge
        draw.ellipse([x+card_w//2-18, top_y+10, x+card_w//2+18, top_y+46], fill=GOLD)
        draw.text((x+card_w//2, top_y+28), num, font=font(17), fill=BG, anchor="mm")

        # title
        draw.text((x+card_w//2, top_y+60), title, font=font(15), fill=WHITE, anchor="mm")

        # desc
        desc_y = top_y + 80
        wrap_text(draw, desc, x+8, desc_y, card_w-16, font(12), fill=GRAY_TEXT, line_height=18)

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-02-stats.webp")

# ─── DIAGRAM 03 — COMPARISON (เสียเปรียบอย่างไร) ─────────────────────────────

def gen_03():
    img, draw = make_canvas()
    draw_header(draw, "Section 03 — ธุรกิจไม่ใช้ AI เสียเปรียบอย่างไร ในชีวิตจริง", "Real-world Impact")

    rows = [
        ("ด้าน", "ใช้ AI", "ไม่ใช้ AI"),
        ("เวลาตอบลูกค้า", "< 1 วินาที ตลอด 24 ชม.", "เฉลี่ย 4-8 ชม. ในเวลางาน"),
        ("ต้นทุนต่อ Lead", "ลดลง 30-60%", "คงที่หรือเพิ่มขึ้น"),
        ("ความแม่นยำข้อมูล", "Real-time จาก AI Dashboard", "พลาด 15-30% จากงาน Manual"),
        ("ความเร็วตัดสินใจ", "ภายใน 24 ชม. ด้วย Insight", "รอรายงานสิ้นเดือน"),
        ("การ Scale ธุรกิจ", "เพิ่ม volume ไม่ต้องเพิ่มคน", "ต้องจ้างคนเพิ่มทุกครั้ง"),
    ]

    col_xs   = [30, 210, 480]
    col_ws   = [175, 265, 295]
    top_y    = 98
    row_h    = 52

    for ri, row in enumerate(rows):
        y      = top_y + ri * row_h
        is_hdr = ri == 0
        bg     = GOLD if is_hdr else (DARK_CARD if ri % 2 == 1 else "#162032")

        draw.rectangle([30, y, W-30, y+row_h-2], fill=bg)

        for ci, (text, cx, cw) in enumerate(zip(row, col_xs, col_ws)):
            fill_c = BG if is_hdr else (GOLD if ci == 0 else (GREEN if ci == 1 else RED_SOFT))
            fsize  = 14 if is_hdr else 13
            draw.text((cx+8, y+row_h//2), text, font=font(fsize), fill=fill_c, anchor="lm")

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-03-comparison.webp")

# ─── DIAGRAM 04 — STATS Before/After ─────────────────────────────────────────

def gen_04():
    img, draw = make_canvas()
    draw_header(draw, "Section 04 — SME ไทยที่ใช้ AI แล้ว เปลี่ยนแปลงอะไรบ้าง", "Before / After")

    metrics = [
        ("เวลาตอบ\nลูกค้า",  "8 ชม.", "< 1 นาที", -88),
        ("ต้นทุน\nMarketing", "฿25K/เดือน", "฿15K/เดือน", -40),
        ("Lead\nConversion",  "3%", "8%", +167),
        ("ชั่วโมงงาน\nManual", "160 ชม./เดือน", "40 ชม./เดือน", -75),
    ]

    card_w  = 162
    gap     = 14
    total   = len(metrics) * card_w + (len(metrics)-1) * gap
    start_x = (W - total) // 2
    top_y   = 105

    for i, (label, before, after, pct) in enumerate(metrics):
        x  = start_x + i * (card_w + gap)
        ch = 330
        draw.rectangle([x, top_y, x+card_w, top_y+ch], fill=DARK_CARD, outline=GOLD, width=1)

        # label
        draw.text((x+card_w//2, top_y+18), label, font=font(13), fill=GOLD,
                  anchor="mm", align="center")

        # before box
        draw.rectangle([x+10, top_y+55, x+card_w-10, top_y+115], fill="#7F1D1D")
        draw.text((x+card_w//2, top_y+68), "ก่อน", font=font(11), fill=WHITE, anchor="mm")
        draw.text((x+card_w//2, top_y+93), before, font=font(17), fill=WHITE, anchor="mm")

        # arrow
        draw.text((x+card_w//2, top_y+128), "▼", font=font(18), fill=GOLD, anchor="mm")

        # after box
        draw.rectangle([x+10, top_y+148, x+card_w-10, top_y+208], fill="#14532D")
        draw.text((x+card_w//2, top_y+161), "หลัง", font=font(11), fill=WHITE, anchor="mm")
        draw.text((x+card_w//2, top_y+186), after, font=font(17), fill=WHITE, anchor="mm")

        # % change
        pct_color = GREEN if pct > 0 else RED_SOFT
        pct_sign  = "+" if pct > 0 else ""
        draw.text((x+card_w//2, top_y+ch-22), f"{pct_sign}{pct}%", font=font(14),
                  fill=pct_color, anchor="mm")

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-04-before-after.webp")

# ─── DIAGRAM 05 — STEPS (7-day plan) ─────────────────────────────────────────

def gen_05():
    img, draw = make_canvas()
    draw_header(draw, "Section 05 — เริ่มใช้ AI Automation ได้ภายใน 1 สัปดาห์", "7-Day Action Plan")

    steps = [
        ("วัน 1", "ระบุ Pain Point", "เลือก 1 งานที่เสียเวลามากที่สุด"),
        ("วัน 2", "เลือก AI Tool", "จับคู่ปัญหากับเครื่องมือที่เหมาะสม"),
        ("วัน 3", "ทดสอบ Free Trial", "ลองใช้งานจริงกับข้อมูลธุรกิจคุณ"),
        ("วัน 4", "ปรับ Workflow", "ออกแบบกระบวนการทำงานใหม่ร่วมกับ AI"),
        ("วัน 5", "Train ทีม", "สอนทีม 1-2 คนให้ใช้ระบบได้"),
        ("วัน 6", "Go Live แบบ Soft", "เริ่มใช้จริงกับ 20% ของงาน"),
        ("วัน 7", "วัดผล & ปรับ", "เปรียบเทียบตัวเลขก่อน-หลัง ปรับต่อ"),
    ]

    node_r  = 22
    step_w  = (W - 80) / len(steps)
    cy_node = 195
    cy_card = 260
    card_h  = 110

    for i, (day, title, desc) in enumerate(steps):
        cx = 40 + i * step_w + step_w / 2

        # connector line
        if i < len(steps) - 1:
            draw.line([cx + node_r, cy_node, cx + step_w - node_r, cy_node],
                      fill=GOLD, width=2)

        # circle
        draw.ellipse([cx-node_r, cy_node-node_r, cx+node_r, cy_node+node_r],
                     fill=GOLD)
        draw.text((cx, cy_node), str(i+1), font=font(15), fill=BG, anchor="mm")

        # day label
        draw.text((cx, cy_node - node_r - 22), day, font=font(11), fill=GOLD, anchor="mm")

        # card
        cx_box = cx - step_w/2 + 4
        draw.rectangle([cx_box, cy_card, cx_box + step_w - 8, cy_card + card_h],
                       fill=DARK_CARD, outline=GOLD, width=1)
        draw.text((cx, cy_card + 16), title, font=font(13), fill=WHITE, anchor="mm")
        wrap_text(draw, desc, cx_box+8, cy_card+36, step_w-20, font(11), fill=GRAY_TEXT, line_height=17)

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-05-steps.webp")

# ─── DIAGRAM 06 — CONCEPT Q&A Cards ──────────────────────────────────────────

def gen_06():
    img, draw = make_canvas()
    draw_header(draw, "Section 06 — FAQ คำถามที่ SME ไทยถามบ่อย", "Frequently Asked Questions")

    faqs = [
        ("AI แพงไหม?", "เริ่มต้นได้ตั้งแต่ ฿0\nหลายเครื่องมือมี Free tier"),
        ("ต้องรู้ coding ไหม?", "ไม่ต้องเลย\nมีระบบ No-code / Low-code"),
        ("ใช้เวลานานแค่ไหน?", "Setup ภายใน 1 สัปดาห์\nเห็นผลภายใน 1 เดือน"),
        ("ข้อมูลปลอดภัยไหม?", "ใช้ Cloud ที่ผ่าน ISO 27001\nกำหนดสิทธิ์ได้เอง"),
        ("ทีมเล็กใช้ได้ไหม?", "เหมาะสุดสำหรับทีม 5-20 คน\nช่วยให้ทำงานได้มากขึ้น"),
        ("เริ่มจากตรงไหน?", "เลือก 1 งานซ้ำซากก่อน\nแล้วค่อย ๆ ขยาย"),
    ]

    cols   = 3
    rows   = 2
    pad    = 16
    cw     = (W - pad*(cols+1)) // cols
    ch     = (H - 100 - pad*(rows+1) - 40) // rows
    top_y  = 100

    for i, (q, a) in enumerate(faqs):
        col = i % cols
        row = i // cols
        x   = pad + col * (cw + pad)
        y   = top_y + pad + row * (ch + pad)

        draw.rectangle([x, y, x+cw, y+ch], fill=DARK_CARD, outline=GOLD, width=2)
        # Q label badge
        draw.rectangle([x, y, x+26, y+26], fill=GOLD)
        draw.text((x+13, y+13), "Q", font=font(14), fill=BG, anchor="mm")
        # Question
        draw.text((x+34, y+10), q, font=font(14), fill=GOLD)
        # Answer
        wrap_text(draw, a, x+12, y+38, cw-24, font(13), fill=WHITE, line_height=20)

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-06-faq.webp")

# ─── DIAGRAM 07 — CONCEPT CTA Visual ─────────────────────────────────────────

def gen_07():
    img, draw = make_canvas()

    # gradient-like background strips
    for band in range(20):
        alpha_val = int(20 + band * 4)
        y_start   = band * (H // 20)
        color     = f"#0F{hex(23 + band)[2:].zfill(2)}3A"
        try:
            draw.rectangle([0, y_start, W, y_start + H//20 + 1], fill=color)
        except Exception:
            pass

    draw.rectangle([0, 0, W, 6], fill=GOLD)

    # Main headline
    draw.text((W//2, 90), "ช่องว่างยิ่งกว้างขึ้นทุกวัน", font=font(28), fill=WHITE, anchor="mm")
    draw.text((W//2, 130), "ที่คุณรอ", font=font(22), fill=GRAY_TEXT, anchor="mm")

    # Gap visual bar
    bar_y    = 170
    bar_h_px = 44

    # competitor bar (full)
    draw.rectangle([60, bar_y, W//2 - 10, bar_y + bar_h_px], fill=GOLD)
    draw.text((60 + (W//2 - 70)//2, bar_y + bar_h_px//2), "คู่แข่ง (ใช้ AI)",
              font=font(14), fill=BG, anchor="mm")

    # your bar (shorter)
    short_end = 60 + int((W//2 - 70) * 0.45)
    draw.rectangle([W//2 + 10, bar_y, W//2 + 10 + int((W//2 - 70) * 0.45), bar_y + bar_h_px],
                   fill="#7F1D1D")
    draw.text((W//2 + 10 + int((W//2 - 70) * 0.45)//2, bar_y + bar_h_px//2),
              "คุณ (ยังไม่ใช้)", font=font(14), fill=WHITE, anchor="mm")

    # arrow gap label
    draw.text((W//2 + 10 + int((W//2 - 70) * 0.45) + 10, bar_y + bar_h_px//2),
              "← ช่องว่าง →", font=font(13), fill=RED_SOFT, anchor="lm")

    # 3 CTA action boxes
    actions = [
        ("1", "ปรึกษาฟรี 30 นาที", "ไม่มีค่าใช้จ่าย"),
        ("2", "รับ AI Audit Report", "วิเคราะห์ธุรกิจคุณ"),
        ("3", "เริ่ม Pilot ใน 7 วัน", "เห็นผลก่อนตัดสินใจ"),
    ]

    box_w    = 210
    box_h    = 110
    gap_b    = 24
    total_bw = len(actions) * box_w + (len(actions)-1) * gap_b
    bx_start = (W - total_bw) // 2
    box_top  = 255

    for i, (num, title, sub) in enumerate(actions):
        bx = bx_start + i * (box_w + gap_b)
        draw.rectangle([bx, box_top, bx+box_w, box_top+box_h], fill=DARK_CARD, outline=GOLD, width=2)
        draw.ellipse([bx+box_w//2-18, box_top+8, bx+box_w//2+18, box_top+44], fill=GOLD)
        draw.text((bx+box_w//2, box_top+26), num, font=font(17), fill=BG, anchor="mm")
        draw.text((bx+box_w//2, box_top+62), title, font=font(14), fill=WHITE, anchor="mm")
        draw.text((bx+box_w//2, box_top+84), sub, font=font(12), fill=GRAY_TEXT, anchor="mm")

    # bottom CTA line
    draw.text((W//2, box_top + box_h + 28),
              "Line: @noodeebootbiz  |  noodeebootbiz.com",
              font=font(14), fill=GOLD, anchor="mm")

    draw_footer(draw)
    save_webp(img, "competitor-ai-sme-thai-07-cta.webp")

# ─── MAIN ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Generating diagrams for article ID 8 ...")
    print()

    generators = [
        ("01", "Comparison — คู่แข่ง vs คุณ",       gen_01),
        ("02", "Stats — 5 สัญญาณตกขบวน AI",          gen_02),
        ("03", "Comparison — เสียเปรียบในชีวิตจริง", gen_03),
        ("04", "Before/After — SME ไทยที่ใช้ AI",    gen_04),
        ("05", "Steps — 7-Day Plan",                  gen_05),
        ("06", "FAQ — Q&A Cards",                     gen_06),
        ("07", "CTA Visual — เริ่มต้นวันนี้",         gen_07),
    ]

    for num, label, fn in generators:
        print(f"[{num}] {label}")
        try:
            fn()
        except Exception as e:
            print(f"  ERROR: {e}")
        print()

    print("Done. All diagrams saved to scripts/article_assets/")
