# Generated by Django 6.0.5 on 2026-05-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="ชื่อ Prompt")),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("chief-of-staff", "Chief of Staff"),
                            ("hustler-sales", "Hustler (Sales)"),
                            ("ai-orchestrator", "AI Orchestrator"),
                            ("money-manager", "Money Manager"),
                            ("ai-toolsmith", "AI Toolsmith"),
                            ("qa-agent", "QA Agent"),
                            ("marketing-specialist", "Marketing Specialist"),
                            ("customer-success", "Customer Success"),
                            ("data-analyst", "Data Analyst"),
                            ("legal-advisor", "Legal Advisor"),
                            ("seo-specialist", "SEO Specialist"),
                            ("content-writer-th", "Content Writer (TH)"),
                            ("frontend-designer", "Frontend Designer"),
                        ],
                        max_length=30,
                        verbose_name="Agent",
                    ),
                ),
                ("use_case", models.CharField(max_length=200, verbose_name="Use Case")),
                ("prompt_text", models.TextField(verbose_name="Prompt")),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("good", "ดีมาก"),
                            ("ok", "พอใช้"),
                            ("needs_work", "ควรปรับปรุง"),
                        ],
                        default="ok",
                        max_length=12,
                        verbose_name="Rating",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompt Library",
                "ordering": ["agent", "use_case"],
            },
        ),
        migrations.CreateModel(
            name="QALog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(max_length=100, verbose_name="ประเภท Output"),
                ),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("chief-of-staff", "Chief of Staff"),
                            ("hustler-sales", "Hustler (Sales)"),
                            ("ai-orchestrator", "AI Orchestrator"),
                            ("money-manager", "Money Manager"),
                            ("ai-toolsmith", "AI Toolsmith"),
                            ("marketing-specialist", "Marketing Specialist"),
                            ("customer-success", "Customer Success"),
                            ("data-analyst", "Data Analyst"),
                            ("legal-advisor", "Legal Advisor"),
                            ("seo-specialist", "SEO Specialist"),
                            ("content-writer-th", "Content Writer (TH)"),
                            ("frontend-designer", "Frontend Designer"),
                        ],
                        max_length=30,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("partial", "Partial"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=10,
                        verbose_name="ผลการ QA",
                    ),
                ),
                (
                    "issue_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("functional", "Functional"),
                            ("security", "Security"),
                            ("ui_ux", "UI/UX"),
                            ("data", "Data"),
                            ("performance", "Performance"),
                            ("compliance", "Compliance"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="หมวดปัญหา",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("cosmetic", "Cosmetic"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="ความรุนแรง",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="บันทึก / รายละเอียดปัญหา"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ตรวจสอบเมื่อ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "QA Log",
                "verbose_name_plural": "QA Logs",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="ชื่อโปรเจกต์"),
                ),
                (
                    "tech_stack",
                    models.JSONField(default=list, verbose_name="Tech Stack"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scoping", "Scoping"),
                            ("dev", "Development"),
                            ("testing", "Testing"),
                            ("live", "Live"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="scoping",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "go_live_date",
                    models.DateField(blank=True, null=True, verbose_name="วัน Go-Live"),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ค่าบริการรายเดือน (บาท)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="รายละเอียด")),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_projects",
                        to="crm.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Project",
                "verbose_name_plural": "AI Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
