# Generated by Django 6.0.5 on 2026-08-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("pages", "0009_homefaq_homepage_homepain_homeprocess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproject",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="ผูกกับบริการบนเว็บ ใช้จัดกลุ่มในหน้า Project Monitor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="pages.service",
                verbose_name="บริการที่ขาย",
            ),
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="เช่น QueueFlow Demo, Bergen Production",
                        max_length=120,
                        verbose_name="ชื่อ Instance",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("dev", "Development"),
                        ],
                        default="production",
                        max_length=12,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "server_host",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Server / IP"
                    ),
                ),
                (
                    "project_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Path บน server"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="systemd service"
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="เว้นว่างได้ถ้ายังไม่ผูก domain — จะข้ามการเช็ค",
                        max_length=300,
                        verbose_name="URL หลัก",
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="Git repo"
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, default="main", max_length=80, verbose_name="Branch"
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(default=True, verbose_name="เปิดการเฝ้าดู"),
                ),
                (
                    "health_path",
                    models.CharField(
                        default="/",
                        help_text="ยิง GET ไปที่ base_url + path นี้",
                        max_length=200,
                        verbose_name="Path สำหรับเช็คว่ามีชีวิต",
                    ),
                ),
                (
                    "monitor_path",
                    models.CharField(
                        blank=True,
                        help_text="เช่น /api/monitor/ — เว้นว่างถ้าระบบยังไม่รองรับ",
                        max_length=200,
                        verbose_name="Path API ตัวเลขธุรกิจ",
                    ),
                ),
                (
                    "monitor_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Bearer token"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False, verbose_name="ระบบลูกค้าจริง (ห้ามแตะข้อมูล)"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="ระบบภายในของเราเอง"
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ค่าดูแล/เดือน (บาท)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="operations.aiproject",
                        verbose_name="โปรเจกต์",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment",
                "verbose_name_plural": "Deployments",
                "ordering": ["project__project_name", "environment", "name"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="ตรวจเมื่อ"
                    ),
                ),
                ("is_up", models.BooleanField(default=False, verbose_name="ขึ้นอยู่")),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="HTTP status"
                    ),
                ),
                (
                    "response_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="เวลาตอบสนอง (ms)"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="ข้อผิดพลาด")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="เวอร์ชัน / commit"
                    ),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deploy เมื่อ"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"key","label","value","unit","alert"}]',
                        verbose_name="ตัวเลขธุรกิจ",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="operations.deployment",
                        verbose_name="Deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Check",
                "verbose_name_plural": "Health Checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "-checked_at"],
                        name="operations__deploym_294ad4_idx",
                    )
                ],
            },
        ),
    ]
